version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodata

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"

  eureka:
    image: misha121212124/eureka-service
    container_name: eureka
    expose:
      - 8761
    ports:
      - 8761:8761

  gateway:
    image: misha121212124/gateway-service
    container_name: gateway
    expose:
      - 8080
    ports:
      - 8080:8080

  auth:
    image: misha121212124/auth-service
    container_name: auth
    expose:
      - 8999
    ports:
      - 8999:8999


  patient:
    image: misha121212124/patient-service
    container_name: patient
    expose:
      - 9001
    ports:
      - 9001:9001

  order:
    image: misha121212124/order-service
    container_name: order
    expose:
      - 9002
    ports:
      - 9002:9002


