server:
  port: 8999

spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: users
      authentication-database: admin
      host: localhost
      port: 27017
      auto-index-creation: true
  application:
    name: authorization-service
eureka:
  instance:
    appname: authorization-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    enabled: true
    path: /v2/api-docs
  swagger-ui:
    path: /swagger-ui