server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

eureka:
  instance:
    appname: gateway-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

route:
  patient-service:
    enabled: true
    path: http://localhost:9001
  order-service:
    enabled: true
    path: http://localhost:9002
  auth-service:
    enabled: true
    path: http://localhost:8999