server:
  port: 9002

spring:
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
  kafka:
    consumer:
      bootstarp-servers: localhost:9092
      group-id: "order_group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstarp-servers: locahost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      username: admin
      password: admin
      database: orders
      authentication-database: admin
      host: localhost
      port: 27017
      auto-index-creation: true
  application:
    name: order-service
eureka:
  instance:
    appname: order-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springfox:
  documentation:
    swagger:
      v2:
        host: localhost:9002
springdoc:
  api-docs:
    enabled: true
    path: /v2/api-docs
  swagger-ui:
    path: /swagger-ui